from __future__ import annotations

import hashlib
import json
import uuid
from typing import Any, Mapping, Sequence

from .models import DistillationProfile, DistilledRule, PredicateAtom


def atom_to_predicate(atom: PredicateAtom) -> dict[str, Any]:
    predicate: dict[str, Any] = {
        "field": atom.field,
        "op": atom.operator,
    }
    if atom.operator not in {"blank", "not_blank", "is_true", "is_false"}:
        predicate["value"] = atom.value
    return predicate


def predicates_to_json(predicates: Sequence[PredicateAtom]) -> dict[str, Any]:
    values = [atom_to_predicate(atom) for atom in predicates]
    if not values:
        return {"all": []}
    if len(values) == 1:
        return values[0]
    return {"all": values}


def outputs_to_actions(
    outputs: Mapping[str, Any],
    profile: DistillationProfile,
) -> list[dict[str, Any]]:
    output_contract = {item.target: item for item in profile.output_fields}
    actions: list[dict[str, Any]] = []
    for target, value in outputs.items():
        contract = output_contract.get(target)
        if contract is None:
            continue
        actions.append({"type": contract.action_type, "value": value})
    return actions


def _stable_uuid(value: str) -> str:
    return str(uuid.uuid5(uuid.NAMESPACE_URL, f"one-engine:{value}"))


def rule_to_catalog_entry(
    rule: DistilledRule,
    profile: DistillationProfile,
    *,
    run_id: str,
    holdout_accuracy: float,
    deployment_eligible: bool,
) -> dict[str, Any]:
    evidence_digest = hashlib.sha256(
        "|".join(sorted(rule.evidence_ids)).encode("utf-8")
    ).hexdigest()
    variant_id = _stable_uuid(f"{profile.profile_id}:{rule.rule_id}:variant")
    rule_uuid = _stable_uuid(f"{profile.profile_id}:{rule.rule_id}")
    status = "approved" if deployment_eligible else "draft"
    automation_level = "alpha" if rule.kind == "general" else "evidence"
    source = {
        "kind": "rules_distillery",
        "ruleset_id": profile.profile_id,
        "ruleset_version": profile.version,
        "distillation_run_id": run_id,
        "distilled_rule_kind": rule.kind,
        "support": rule.support,
        "confidence": rule.confidence,
        "holdout_accuracy": holdout_accuracy if rule.kind == "general" else 0.0,
        "source_groups": list(rule.source_groups),
        "evidence_count": len(rule.evidence_ids),
        "evidence_sha256": evidence_digest,
    }
    return {
        "id": rule_uuid,
        "rule_id": rule.rule_id,
        "name": (
            f"{profile.profile_id.replace('_', ' ').title()} "
            f"{rule.kind.title()} Decision"
        ),
        "rule_group": f"Rules Distillery · {profile.profile_id}",
        "business_scope": "Profile-defined",
        "request_types": [],
        "discovery_reference": "Mechanized BEFORE/AFTER distillation",
        "notes": (
            "Generated by Rules Distillery. General rules are filter-derived; "
            "evidence rules close deterministic historical residuals."
        ),
        "owner_team": "ONE ENGINE",
        "status": status,
        "automation_level": automation_level,
        "is_bundled": False,
        "ruleset_id": profile.profile_id,
        "distillation_run_id": run_id,
        "variants": [
            {
                "id": variant_id,
                "rule_id": rule.rule_id,
                "runtime_rule_id": f"{rule.rule_id}.01",
                "runtime_kind": "row_rule",
                "execution_priority": rule.priority,
                "enabled": deployment_eligible,
                "is_executable": True,
                "stop_processing": True,
                "predicate_json": predicates_to_json(
                    (
                        PredicateAtom(
                            "__ruleset_id",
                            "eq",
                            profile.profile_id,
                        ),
                        *rule.predicates,
                    )
                ),
                "action_json": outputs_to_actions(rule.outputs, profile),
                "description": (
                    f"Distilled {rule.kind} rule with support {rule.support:,} "
                    f"and confidence {rule.confidence:.3f}"
                ),
                "automation_level": automation_level,
                "status": status,
                "source": source,
            }
        ],
        "source": source,
    }


def build_catalog(
    rules: Sequence[DistilledRule],
    profile: DistillationProfile,
    *,
    run_id: str,
    holdout_accuracy: float,
    deployment_eligible: bool = True,
) -> list[dict[str, Any]]:
    return [
        rule_to_catalog_entry(
            rule,
            profile,
            run_id=run_id,
            holdout_accuracy=holdout_accuracy,
            deployment_eligible=deployment_eligible,
        )
        for rule in sorted(rules, key=lambda item: item.priority)
    ]


def build_snowflake_merge_sql(
    catalog: Sequence[Mapping[str, Any]],
    *,
    table_name: str = (
        "FOODBUY_MASALA_PROD.COMPLIANCE_LAB.COMPLIANCE_RULES_RULES"
    ),
) -> str:
    payload = json.dumps(catalog, ensure_ascii=False, separators=(",", ":"))
    if "$$" in payload:
        raise ValueError("Catalog payload collides with the Snowflake delimiter")
    if not catalog:
        raise ValueError("Cannot emit a Snowflake catalog loader with no rules")
    source = catalog[0].get("source") or {}
    profile_id = str(source.get("ruleset_id") or "").replace("'", "''")
    run_id = str(source.get("distillation_run_id") or "").replace("'", "''")
    return f"""-- Generated by ONE ENGINE Rules Distillery.
BEGIN;

-- Retire generated rules from earlier runs of this ruleset. The MERGE below
-- restores current rules, preventing removed logic from remaining executable.
UPDATE {table_name}
SET
    STATUS = 'retired',
    UPDATED_AT = CURRENT_TIMESTAMP(),
    RULE_JSON = OBJECT_INSERT(
        OBJECT_INSERT(RULE_JSON, 'status', TO_VARIANT('retired'), TRUE),
        'variants',
        ARRAY_CONSTRUCT(
            OBJECT_INSERT(
                OBJECT_INSERT(
                    RULE_JSON:"variants"[0]::OBJECT,
                    'status',
                    TO_VARIANT('retired'),
                    TRUE
                ),
                'enabled',
                TO_VARIANT(FALSE),
                TRUE
            )
        ),
        TRUE
    )
WHERE RULE_JSON:"source":"kind"::VARCHAR = 'rules_distillery'
  AND RULE_JSON:"source":"ruleset_id"::VARCHAR = '{profile_id}'
  AND COALESCE(
      RULE_JSON:"source":"distillation_run_id"::VARCHAR,
      ''
  ) <> '{run_id}';

MERGE INTO {table_name} AS target
USING (
    SELECT
        value:"id"::VARCHAR AS ID,
        value:"rule_id"::VARCHAR AS RULE_ID,
        value:"name"::VARCHAR AS NAME,
        value:"rule_group"::VARCHAR AS RULE_GROUP,
        value:"status"::VARCHAR AS STATUS,
        value:"automation_level"::VARCHAR AS AUTOMATION_LEVEL,
        COALESCE(value:"variants"[0]:"execution_priority"::NUMBER, 0)
            AS EXECUTION_PRIORITY,
        COALESCE(value:"is_bundled"::BOOLEAN, FALSE) AS IS_BUNDLED,
        CURRENT_TIMESTAMP() AS UPDATED_AT,
        value AS RULE_JSON
    FROM TABLE(
        FLATTEN(
            INPUT => PARSE_JSON(
$$
{payload}
$$
            )
        )
    )
) AS source
ON target.RULE_ID = source.RULE_ID
WHEN MATCHED THEN UPDATE SET
    ID = source.ID,
    NAME = source.NAME,
    RULE_GROUP = source.RULE_GROUP,
    STATUS = source.STATUS,
    AUTOMATION_LEVEL = source.AUTOMATION_LEVEL,
    EXECUTION_PRIORITY = source.EXECUTION_PRIORITY,
    IS_BUNDLED = source.IS_BUNDLED,
    UPDATED_AT = source.UPDATED_AT,
    RULE_JSON = source.RULE_JSON
WHEN NOT MATCHED THEN INSERT (
    ID,
    RULE_ID,
    NAME,
    RULE_GROUP,
    STATUS,
    AUTOMATION_LEVEL,
    EXECUTION_PRIORITY,
    IS_BUNDLED,
    UPDATED_AT,
    RULE_JSON
) VALUES (
    source.ID,
    source.RULE_ID,
    source.NAME,
    source.RULE_GROUP,
    source.STATUS,
    source.AUTOMATION_LEVEL,
    source.EXECUTION_PRIORITY,
    source.IS_BUNDLED,
    source.UPDATED_AT,
    source.RULE_JSON
);

COMMIT;
"""
